// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/slok/kube-code-generator/example/apis/comic/v1"
	scheme "github.com/slok/kube-code-generator/example/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HerosGetter has a method to return a HeroInterface.
// A group's client should implement this interface.
type HerosGetter interface {
	Heros() HeroInterface
}

// HeroInterface has methods to work with Hero resources.
type HeroInterface interface {
	Create(ctx context.Context, hero *v1.Hero, opts metav1.CreateOptions) (*v1.Hero, error)
	Update(ctx context.Context, hero *v1.Hero, opts metav1.UpdateOptions) (*v1.Hero, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hero *v1.Hero, opts metav1.UpdateOptions) (*v1.Hero, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Hero, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.HeroList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Hero, err error)
	HeroExpansion
}

// heros implements HeroInterface
type heros struct {
	*gentype.ClientWithList[*v1.Hero, *v1.HeroList]
}

// newHeros returns a Heros
func newHeros(c *ComicV1Client) *heros {
	return &heros{
		gentype.NewClientWithList[*v1.Hero, *v1.HeroList](
			"heros",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1.Hero { return &v1.Hero{} },
			func() *v1.HeroList { return &v1.HeroList{} }),
	}
}
