version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore Kubernetes dependencies to have full control on them.
      - dependency-name: "k8s.io/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/dev"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/prod"
    schedule:
      interval: "daily"
