// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HeroStatusApplyConfiguration represents a declarative configuration of the HeroStatus type for use
// with apply.
type HeroStatusApplyConfiguration struct {
	Moving      *bool   `json:"moving,omitempty"`
	CurrentCity *string `json:"currentCity,omitempty"`
}

// HeroStatusApplyConfiguration constructs a declarative configuration of the HeroStatus type for use with
// apply.
func HeroStatus() *HeroStatusApplyConfiguration {
	return &HeroStatusApplyConfiguration{}
}

// WithMoving sets the Moving field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Moving field is set to the value of the last call.
func (b *HeroStatusApplyConfiguration) WithMoving(value bool) *HeroStatusApplyConfiguration {
	b.Moving = &value
	return b
}

// WithCurrentCity sets the CurrentCity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentCity field is set to the value of the last call.
func (b *HeroStatusApplyConfiguration) WithCurrentCity(value string) *HeroStatusApplyConfiguration {
	b.CurrentCity = &value
	return b
}
