// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apiscomicv1 "github.com/slok/kube-code-generator/example/apis/comic/v1"
	versioned "github.com/slok/kube-code-generator/example/client/clientset/versioned"
	internalinterfaces "github.com/slok/kube-code-generator/example/client/informers/externalversions/internalinterfaces"
	comicv1 "github.com/slok/kube-code-generator/example/client/listers/comic/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HeroInformer provides access to a shared informer and lister for
// Heros.
type HeroInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() comicv1.HeroLister
}

type heroInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewHeroInformer constructs a new informer for Hero type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHeroInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHeroInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredHeroInformer constructs a new informer for Hero type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHeroInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ComicV1().Heros().List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ComicV1().Heros().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ComicV1().Heros().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ComicV1().Heros().Watch(ctx, options)
			},
		},
		&apiscomicv1.Hero{},
		resyncPeriod,
		indexers,
	)
}

func (f *heroInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHeroInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *heroInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiscomicv1.Hero{}, f.defaultInformer)
}

func (f *heroInformer) Lister() comicv1.HeroLister {
	return comicv1.NewHeroLister(f.Informer().GetIndexer())
}
