// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/slok/kube-code-generator/example/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Heros returns a HeroInformer.
	Heros() HeroInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Heros returns a HeroInformer.
func (v *version) Heros() HeroInformer {
	return &heroInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
