// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/slok/kube-code-generator/example/client/clientset/versioned/typed/comic/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeComicV1 struct {
	*testing.Fake
}

func (c *FakeComicV1) Heros() v1.HeroInterface {
	return &FakeHeros{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeComicV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
